-- MySQL Script generated by MySQL Workbench
-- Tue Oct 18 00:45:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Domicilio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Domicilio` (
  `IdDomicilio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(45) NULL,
  `Numero` VARCHAR(10) NULL,
  `Piso` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Barrio` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `EntreCalles` VARCHAR(100) NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`IdDomicilio`, `Persona_idPersona`),
  CONSTRAINT `fk_Domicilio_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdDomicilio_UNIQUE` ON `mydb`.`Domicilio` (`IdDomicilio` ASC) VISIBLE;

CREATE INDEX `fk_Domicilio_Persona1_idx` ON `mydb`.`Domicilio` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Educacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Educacion` (
  `idInstitucion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombreInstitucion` VARCHAR(45) NOT NULL,
  `AñoInicio` INT NOT NULL,
  `AñoFin` INT NULL,
  `Nivel` VARCHAR(45) NOT NULL,
  `UbicacionImagenLogo` VARCHAR(200) NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idInstitucion`, `Persona_idPersona`),
  CONSTRAINT `fk_Educacion_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Educacion_Persona1_idx` ON `mydb`.`Educacion` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ExperienciaLaboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExperienciaLaboral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ExperienciaLaboral` (
  `idExperienciaLaboral` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `AñoDesde` INT NOT NULL,
  `AñoHasta` INT NULL,
  `CargoInicio` VARCHAR(45) NOT NULL,
  `CargoAlcanzado` VARCHAR(45) NOT NULL,
  `TareasDesarrolladas` VARCHAR(150) NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idExperienciaLaboral`, `Persona_idPersona`),
  CONSTRAINT `fk_ExperienciaLaboral_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ExperienciaLaboral_Persona1_idx` ON `mydb`.`ExperienciaLaboral` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Habilidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades` (
  `idHabilidades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Porcentaje` DECIMAL NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  `Tecnologia_idTecnologia` INT NOT NULL,
  PRIMARY KEY (`idHabilidades`, `Persona_idPersona`, `Tecnologia_idTecnologia`),
  CONSTRAINT `fk_Habilidades_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Habilidades_Tecnologia1`
    FOREIGN KEY (`Tecnologia_idTecnologia`)
    REFERENCES `mydb`.`Tecnologia` (`idTecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idHabilidades_UNIQUE` ON `mydb`.`Habilidades` (`idHabilidades` ASC) VISIBLE;

CREATE INDEX `fk_Habilidades_Persona1_idx` ON `mydb`.`Habilidades` (`Persona_idPersona` ASC) VISIBLE;

CREATE INDEX `fk_Habilidades_Tecnologia1_idx` ON `mydb`.`Habilidades` (`Tecnologia_idTecnologia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ubicacion_foto` LONGTEXT NOT NULL,
  `SobreMi` VARCHAR(400) NOT NULL,
  `FechaNacimiento` DATE NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPersona_UNIQUE` ON `mydb`.`Persona` (`idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `TituloProyecto` VARCHAR(45) NOT NULL,
  `UbicacionImagenProyecto` VARCHAR(200) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `AñoRealizado` INT NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProyectos`, `Persona_idPersona`),
  CONSTRAINT `fk_Proyectos_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProyectos_UNIQUE` ON `mydb`.`Proyectos` (`idProyectos` ASC) VISIBLE;

CREATE INDEX `fk_Proyectos_Persona1_idx` ON `mydb`.`Proyectos` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tecnologia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tecnologia` (
  `idTecnologia` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `UbicacionImagenLogo` LONGTEXT NULL,
  PRIMARY KEY (`idTecnologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(20) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idUsuario`, `Persona_idPersona`),
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idUsuario_UNIQUE` ON `mydb`.`Usuario` (`idUsuario` ASC) VISIBLE;

CREATE INDEX `fk_Usuario_Persona1_idx` ON `mydb`.`Usuario` (`Persona_idPersona` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`certificados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`certificados` ;

CREATE TABLE IF NOT EXISTS `mydb`.`certificados` (
  `idcertificados` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `UbicacionImagenCertif` VARCHAR(200) NULL,
  `titulocertificado` VARCHAR(45) NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idcertificados`, `Persona_idPersona`),
  CONSTRAINT `fk_certificados_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idcertificados_UNIQUE` ON `mydb`.`certificados` (`idcertificados` ASC) VISIBLE;

CREATE INDEX `fk_certificados_Persona1_idx` ON `mydb`.`certificados` (`Persona_idPersona` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
