-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 01:43:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Domicilio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Domicilio` (
  `IdDomicilio` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Calle` VARCHAR(45) NULL,
  `Numero` VARCHAR(10) NULL,
  `Piso` VARCHAR(45) NULL,
  `Departamento` VARCHAR(45) NULL,
  `Barrio` VARCHAR(45) NULL,
  `Localidad` VARCHAR(45) NULL,
  `Provincia` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `EntreCalles` INT NULL,
  PRIMARY KEY (`IdDomicilio`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `IdDomicilio_UNIQUE` ON `mydb`.`Domicilio` (`IdDomicilio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Educacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Educacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Educacion` (
  `idInstitucion` INT NOT NULL,
  `NombreInstitucion` VARCHAR(45) NULL,
  `AñoInicio` INT NULL,
  `AñoFin` INT NULL,
  `Nivel` VARCHAR(45) NULL,
  `UbicacionImagenLogo` LONGTEXT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  `Persona_Domicilio_IdDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idInstitucion`, `Persona_idPersona`, `Persona_Domicilio_IdDomicilio`),
  CONSTRAINT `fk_Educacion_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Educacion_Persona1_idx` ON `mydb`.`Educacion` (`Persona_idPersona` ASC, `Persona_Domicilio_IdDomicilio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`ExperienciaLaboral`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ExperienciaLaboral` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ExperienciaLaboral` (
  `idExperienciaLaboral` INT NOT NULL,
  `idPersona` INT NULL,
  `NombreEmpresa` VARCHAR(45) NULL,
  `AñoDesde` INT NULL,
  `AñoHasta` INT NULL,
  `CargoInicio` VARCHAR(45) NULL,
  `CargoAlcanzado` VARCHAR(45) NULL,
  `TareasDesarrolladas` LONGTEXT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  `Persona_Domicilio_IdDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idExperienciaLaboral`, `Persona_idPersona`, `Persona_Domicilio_IdDomicilio`),
  CONSTRAINT `fk_ExperienciaLaboral_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ExperienciaLaboral_Persona1_idx` ON `mydb`.`ExperienciaLaboral` (`Persona_idPersona` ASC, `Persona_Domicilio_IdDomicilio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Habilidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Habilidades` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Habilidades` (
  `idHabilidades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idTecnologia` INT NOT NULL,
  `idPersona` INT NOT NULL,
  `Porcentaje` DECIMAL NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  `Persona_Domicilio_IdDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idHabilidades`, `Persona_idPersona`, `Persona_Domicilio_IdDomicilio`),
  CONSTRAINT `fk_Habilidades_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Habilidades_Persona1_idx` ON `mydb`.`Habilidades` (`Persona_idPersona` ASC, `Persona_Domicilio_IdDomicilio` ASC) VISIBLE;

CREATE UNIQUE INDEX `idHabilidades_UNIQUE` ON `mydb`.`Habilidades` (`idHabilidades` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Apellido` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Ubicacion_foto` LONGTEXT NOT NULL,
  `SobreMi` LONGTEXT NOT NULL,
  `Domicilio_IdDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPersona`, `Domicilio_IdDomicilio`),
  CONSTRAINT `fk_Persona_Domicilio1`
    FOREIGN KEY (`Domicilio_IdDomicilio`)
    REFERENCES `mydb`.`Domicilio` (`IdDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idPersona_UNIQUE` ON `mydb`.`Persona` (`idPersona` ASC) VISIBLE;

CREATE INDEX `fk_Persona_Domicilio1_idx` ON `mydb`.`Persona` (`Domicilio_IdDomicilio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Proyectos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Proyectos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Proyectos` (
  `idProyectos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `NombreProyecto` VARCHAR(45) NOT NULL,
  `UbicacionImagenProyecto` LONGTEXT NULL,
  `Descripcion` LONGTEXT NULL,
  `AñoRealizado` INT NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  `Persona_Domicilio_IdDomicilio` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idProyectos`, `Persona_idPersona`, `Persona_Domicilio_IdDomicilio`),
  CONSTRAINT `fk_Proyectos_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProyectos_UNIQUE` ON `mydb`.`Proyectos` (`idProyectos` ASC) VISIBLE;

CREATE INDEX `fk_Proyectos_Persona1_idx` ON `mydb`.`Proyectos` (`Persona_idPersona` ASC, `Persona_Domicilio_IdDomicilio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`Tecnologia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Tecnologia` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Tecnologia` (
  `idTecnologia` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `UbicacionImagenLogo` LONGTEXT NULL,
  `Habilidades_idHabilidades` INT NOT NULL,
  PRIMARY KEY (`idTecnologia`, `Habilidades_idHabilidades`),
  CONSTRAINT `fk_Tecnologia_Habilidades1`
    FOREIGN KEY (`Habilidades_idHabilidades`)
    REFERENCES `mydb`.`Habilidades` (`idHabilidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Tecnologia_Habilidades1_idx` ON `mydb`.`Tecnologia` (`Habilidades_idHabilidades` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
